steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/$PROJECT_ID/cinema-ec/backend:latest',
        '.',
      ]
    id: 'build'

  # Step 2: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'us-east4-docker.pkg.dev/$PROJECT_ID/cinema-ec/backend:latest']
    id: 'push'
    waitFor: ['build']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=.
      - --image=us-east4-docker.pkg.dev/$PROJECT_ID/cinema-ec/backend:latest
      - --location=us-east4
      - --cluster=cinema-ec
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-east4'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cinema-ec'

  # Step 4: Run migrations
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      [
        'exec',
        '-it',
        'cinema-ec-backend-pod',
        '--',
        'npm',
        'run',
        'migration:run',
      ]
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-east4'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cinema-ec'

images:
  - 'us-east4-docker.pkg.dev/$PROJECT_ID/cinema-ec/backend:latest'

timeout: '1800s'
machineType: 'N1_HIGHCPU_8'
